defaults:
  - _self_
  - override hydra/launcher: submitit_local

# task settings
action_repeat: 2
discount: 0.99
# train settings
num_seed_frames: 0
utd: 1
bc_freq: 2
num_train_frames: 100000
# eval
eval_every_frames: 2000
num_eval_episodes: 50
# snapshot
save_snapshot: false
# replay buffer
replay_buffer_size: 1000000
replay_buffer_num_workers: 4
nstep: 3
batch_size: 256
warmup: 2000
# misc
seed: 1
device: cpu
save_video: true
use_tb: true
# experiment
experiment: exp
# agent
lr: 1e-4

agent:
  _target_: ac.ACAgent
  obs_shape: ??? # to be specified later
  action_shape: ??? # to be specified later
  device: ${device}
  lr: ${lr}
  critic_target_tau: 0.005
  use_tb: ${use_tb}
  hidden_dim: 256
  num_critics: 2
  stddev_clip: 0.3

hydra:
  run:
    dir: ./Logdir/run_${now:%H%M%S}_${hydra.job.override_dirname}
  sweep:
    dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}_${agent_cfg.experiment}
    subdir: ${hydra.job.num}
  launcher:
    timeout_min: 4300
    cpus_per_task: 8
    tasks_per_node: 1
    mem_gb: 160
    nodes: 1
    submitit_folder: ./exp/${now:%Y.%m.%d}/${now:%H%M%S}_${agent_cfg.experiment}/.slurm
